package com.example.mymeal.domain.model

import com.example.mymeal.data.remote.model.RequestExtendedIngredients
import com.example.mymeal.data.remote.model.RequestInformation

data class RecipeInformation(
    val id: Int?,
    val title: String?,
    val image: String?,
    val imageType: String?,
    val servings: Int?,
    val readyInMinutes: Int?,
    val license: String?,
    val sourceName: String?,
    val sourceUrl: String?,
    val spoonacularSourceUrl: String?,
    val aggregateLikes: Int?,
    val healthScore: Int?,
    val spoonacularScore: Double?,
    val pricePerServing: Double?,
    val cheap: Boolean?,
    val creditsText: String?,
    val cuisines: ArrayList<String>?,
    val dairyFree: Boolean?,
    val gaps: String?,
    val glutenFree: Boolean?,
    val instructions: String?,
    val ketogenic: Boolean?,
    val lowFodmap: Boolean?,
    val occasions: ArrayList<String>?,
    val sustainable: Boolean?,
    val vegan: Boolean?,
    val vegetarian: Boolean?,
    val veryHealty: Boolean?,
    val veryPopular: Boolean?,
    val whole30: Boolean?,
    val weightWatcherSmartPoints: Int?,
    val dishTypes: ArrayList<String>?,
    val extendedIngredients: ArrayList<RequestExtendedIngredients>?,
    val summary: String?,
    val preparationMinutes: Int?,
    val cookingMinutes: Int?,
    val diets: ArrayList<String>?
)

fun RequestInformation.toDomain() = RecipeInformation(
    id,
    title,
    image,
    imageType,
    servings,
    readyInMinutes,
    license,
    sourceName,
    sourceUrl,
    spoonacularSourceUrl,
    aggregateLikes,
    healthScore,
    spoonacularScore,
    pricePerServing,
    cheap,
    creditsText,
    cuisines,
    dairyFree,
    gaps,
    glutenFree,
    instructions,
    ketogenic,
    lowFodmap,
    occasions,
    sustainable,
    vegan,
    vegetarian,
    veryHealty,
    veryPopular,
    whole30,
    weightWatcherSmartPoints,
    dishTypes,
    extendedIngredients,
    summary,
    preparationMinutes,
    cookingMinutes,
    diets
)
